In [11]:
import pandas as pd
import numpy as np
df = pd.read_csv('data/alturas-pesos.csv')


In [12]:
df['Peso'].values, df['Altura'].values

(array([61.235, 97.432, 73.324, ..., 75.461, 65.461, 80.323]),
 array([162.402, 181.908, 172.459, ..., 170.91 , 166.137, 171.575]))

In [13]:

class StandardScaler(): #Se usa camel case con mayusculas para una clase
            
    """
    Normaliza un numpy array
    """
    def __init__(self): #La variable self esta reservada y es cuando se refiere a si mismo, es que esta funcion modifica al objeto
        self.mean = 0
        self.std  = 0
        
    def fit(self,X):
        self.mean_ = X.mean()
        self.std_  = X.std()
    
    def transform(self, X):
        return ((X - self.mean_) / self.std_)
        


In [14]:
s_peso = StandardScaler() # self toma el nombre de s_peso

In [15]:
s_peso.mean

0

In [16]:
s_peso.fit(df['Peso'].values)

In [17]:
s_peso.transform(np.array([100, 60, 80, 50]))

array([ 1.85981433, -0.87545572,  0.49217931, -1.55927324])